### PR TITLE
Create .gitignore

### PR DESCRIPTION
**Pull request by kokonut27**
You should probably add this, but the `.gitignore` file will ignore the `__pycache__` directory, which will be helpful.

It will also ignore other future unneeded files, which is helpful as well :)

### CODE REVIEW

**Comment by VulcanWM** [comment]
Thanks!

**Comment by JBYT27** [comment]
No problem! Glad I could help! :D

**Comment by VulcanWM** [comment]
Wait do I have to delete the __pycache__ files first so they get ignored from the next time?

**Comment by JBYT27** [comment]
No, if you do delete them, once you run it on Replit again, it will re-appear anyways. The .gitignore file ignores it for you, so that all the data will be ignored. It won’t delete the file, but it will ignore all the data, which will be helpful.

**Comment by VulcanWM** [comment]
Oh okay thanks

**Pull request merged**
